-- Creación de la base de datos
CREATE DATABASE MUSICA;
USE MUSICA;
--Creación de los esquemas
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;
CREATE SCHEMA PRE_RAW;
CREATE SCHEMA ADM;
CREATE SCHEMA VISTA;
CREATE SCHEMA DW;
-- Creación de la tabla de control de las playlist
 CREATE OR REPLACE TABLE MUSICA.ADM.CONTROL_PLAYLIST (
	ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216),
	SCHEMA_NAME VARCHAR(16777216),
	RECORDS NUMBER(38,0),
	INSERTAR BOOLEAN,
    FECHA_CREACION_CSV TIMESTAMP,
	CREATE_DATE DATE DEFAULT CURRENT_DATE(),
	LAST_UPDATE_DATE DATE DEFAULT CURRENT_DATE()
);   