CREATE DATABASE MUSICA;
USE MUSICA;
CREATE SCHEMA PLAYLIST;
CREATE SCHEMA SETLIST;
CREATE SCHEMA ADM;

create or replace TABLE MUSICA.ADM.CONTROL_PLAYLIST (
	ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
	NAME VARCHAR(16777216),
	SCHEMA_NAME VARCHAR(16777216),
	RECORDS NUMBER(38,0),
	INSERTAR BOOLEAN,
	CREATE_DATE DATE DEFAULT CURRENT_DATE(),
	LAST_UPDATE_DATE DATE DEFAULT CURRENT_DATE()
);